<style>
#photo-wall{ 
    margin: 0 0 1200px 0; 
    padding: 15; 
    max-width: 1200px; 
    list-style: none; 
    overflow: hidden; 
}

#photo-wall li{ 
    float: left; 
    width: 30%; 
    overflow: hidden;
}

#photo-wall li img{ 
    display: block;     
    border-left: 1px solid transparent;
    border-bottom: 1px solid transparent; 
    -webkit-transition: opacity 0.5s ease-out;  /* Saf3.2+, Chrome */
       -moz-transition: opacity 0.5s ease-out;  /* FF4+ */
        -ms-transition: opacity 0.5s ease-out;  /* IE10 */
         -o-transition: opacity 0.5s ease-out;  /* Opera 10.5+ */
            transition: opacity 0.5s ease-out;
}

#photo-wall:hover img{ 
    opacity: .5;  
}

#photo-wall li:hover img{ 
    opacity: 1; 
}

.oldie #photo-wall:hover img{ 
    filter: alpha(opacity=50); /* for older versions of IE */
}

.oldie #photo-wall li:hover img{ 
    filter: alpha(opacity=100); /* for older versions of IE */
}

</style>		
<?php
//echo '<link rel="stylesheet" href="galerie.css" type="text/css">';
$xml = simplexml_load_file('http://picasaweb.google.com/data/feed/base/user/107401320610499259896/albumid/6065229773950541889?alt=rss&kind=photo&authkey=Gv1sRgCNak7e60l-7VlgE&hl=fr');

echo "<h1><center>THYP 14/15</center></h1>";
echo '<ul id="photo-wall">';
foreach ($xml->channel->item as $tof) 
{
		echo "<tr>";
		echo "<td>";

		
	echo "<li><img src='".$tof->enclosure["url"]."' /></sli>";

	
	echo "</td>";
	echo "<td>";
	
		echo $tof->title;
		echo "</td>";
		echo "</tr>";
	echo "</td>";
	echo "<td>";
	echo "<form action='/devoirTHYP1415/ZamelMouhaned/absence/public/ecrire' method='get'>
			<input type='submit' value='absent' name='id_abs'>
			
			
			<input type='submit' value='present'>
			</form>";
	echo "</td>";
		echo "</tr>";
}
echo '</ul>';	
?>


